name: Auto Merge PR

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up GitHub CLI
      uses: github-cli/gh-action@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Check if PR has passed checks
      run: |
        pr_checks=$(gh pr view ${{ github.event.pull_request.number }} --json statusCheckRollup -q ".statusCheckRollup.status")
        if [[ "$pr_checks" == "SUCCESS" ]]; then
          echo "PR passed checks, ready to merge"
        else
          echo "PR has failed checks, not merging"
          exit 1
        fi

    - name: Merge PR if conditions met
      run: |
        gh pr merge ${{ github.event.pull_request.number }} --merge --admin