name: Auto Assign and Merge

on:
  pull_request:
    types: [opened]

jobs:
  assign-and-merge:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Assign Pull Request to Code Rabbit
      - name: Assign PR to Code Rabbit
        uses: vishweshshetty/assign-issue-pr@v1.2.0
        with:
          assignees: coderabbitai # Replace with the actual bot username
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 2: Enable Auto-Merge
      - name: Enable Auto-Merge
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash # Choose "merge", "squash", or "rebase"
