name: Auto Assign Pull Request

on:
  pull_request:
    types: [opened] # Trigger when a new PR is opened

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Assign Pull Request
      - name: Assign PR to Code Rabbit
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              assignees: ['zubsamaj'],
            });
